active1:
  image: "webcenter/activemq:latest"
  hostname: "active1"
  environment:
    ACTIVEMQ_CONFIG_MINMEMORY: "512"
    ACTIVEMQ_CONFIG_MAXMEMORY: "2048"
    ACTIVEMQ_ADMIN_LOGIN: "activemq"
    ACTIVEMQ_ADMIN_PASSWORD: "activemq"
  ports:
    - "61677:61616"
    - "8161:8161"
  labels:
    NAME: "activemq1"
